//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int Id { get; set; }
        public bool Permission1 { get; set; }
        public int Music_fk { get; set; }
        public System.Guid User_fk { get; set; }
    
        public virtual Music Music { get; set; }
        public virtual User User { get; set; }
    }
}
